inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gemfiles/**/*'

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 7

Style/Alias:
  Enabled: false

Style/AndOr:
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  EnforcedStyle: literal

Style/SafeNavigation:
  Enabled: false

Style/WordArray:
  MinSize: 0
